"""Build the Free-plan upload copies of main.py and rules.py.

QuantConnect's web IDE caps each pasted file at 32,000 characters
(README.md, "How to run it"), and main.py/rules.py exceed that once every
comment and docstring is counted. This script writes stripped copies to
research/qc-cloud/dist/ (git-ignored: a build artifact, never the source of
truth read for comments or run for tests) -- module, class and function
docstrings removed by walking the parsed AST, comments dropped as an
unavoidable side effect of regenerating source with ``ast.unparse``.

Usage, from the repository root:

    python3 research/qc-cloud/build_upload.py

Standard library only, so this needs nothing installed beyond the Python 3
(>=3.9, for ``ast.unparse``) already required to run test_rules.py.
"""

import ast
import sys
from pathlib import Path

#: QuantConnect's own Free-plan per-file cap (README.md, "How to run it").
MAX_CHARS = 32_000

HERE = Path(__file__).resolve().parent
DIST = HERE / "dist"
SOURCES = ("main.py", "rules.py")

#: The only node kinds whose leading string-literal statement is a
#: docstring in Python's own sense (``ast.get_docstring`` recognises the
#: same four kinds). A bare string statement anywhere else (inside an
#: ``if``/``for``/``try`` body, for instance) is not a docstring and is
#: left alone.
_DOCSTRING_OWNERS = (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)


def _is_docstring_statement(stmt):
    return (isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str))


def _strip_docstrings(node):
    """Remove ``node``'s own leading docstring statement, if it is a
    Module/ClassDef/FunctionDef/AsyncFunctionDef and has one, then recurse
    into every child node. A class or function body can never be empty, so
    a body left with nothing after its docstring is removed is given a
    single ``pass`` statement in its place."""
    if isinstance(node, _DOCSTRING_OWNERS):
        body = node.body
        if body and _is_docstring_statement(body[0]):
            del body[0]
            if not body:
                body.append(ast.Pass())
    for child in ast.iter_child_nodes(node):
        _strip_docstrings(child)
    return node


def strip_source(source):
    """The given source, with every module/class/function docstring
    removed and then regenerated by ``ast.unparse`` -- which also drops
    every ordinary comment, since comments are not part of the AST."""
    tree = ast.parse(source)
    _strip_docstrings(tree)
    ast.fix_missing_locations(tree)
    return ast.unparse(tree)


def build():
    """Write the stripped copies to dist/ and return {filename: character
    count} for each one written."""
    DIST.mkdir(exist_ok=True)
    sizes = {}
    for name in SOURCES:
        source = (HERE / name).read_text()
        stripped = strip_source(source)
        (DIST / name).write_text(stripped)
        sizes[name] = len(stripped)
    return sizes


def main():
    sizes = build()
    for name, size in sizes.items():
        print("built dist/{} ({} characters)".format(name, size))
    failures = [name for name, size in sizes.items() if size >= MAX_CHARS]
    if failures:
        print(
            "ERROR: still at or over QuantConnect's Free-plan {}-character "
            "per-file limit after stripping docstrings: {}. Trim the source "
            "further (or accept the file cannot fit) before pasting it into "
            "QuantConnect's cloud IDE.".format(MAX_CHARS, ", ".join(failures)),
            file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
